- name: install cron job
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/mujinit/ansible-pull.git > /home/mujin/ansible-pull.log"